### ISSUE TITLE
Does not work in IE11

### ISSUE THREAD

**Issue by artifex404** [LeEnno/stickyHeaders#2]
"Unable to get property 'height' of undefined or null reference" error. Line 112 of the original raw file.

**Comment by LeEnno** [comment]
Is this fixed by #3?

**Comment by artifex404** [comment]
#3 fixed the overall blocker error, the script works... but still throws an error while you scroll to the top of the page.

**Comment by LeEnno** [comment]
closing since it's probably out of date
